PRODUCTS = [
    "Laptop Computer",
    "Tablet Device",
    "Smart Phone",
    "Desktop Computer",
    "Wireless Earbuds",
    "Gaming Console",
    "Computer Monitor",
    "Computer Keyboard",
    "Computer Mouse",
    "Printer Device",
    "Scanner Device",
    "Web Camera",
    "Microphone",
    "Audio Speakers",
    "Network Router",
    "Network Modem",
    "Power Bank",
    "Charging Cable",
    "Phone Case",
    "Screen Protector",
    "External Hard Drive",
    "Solid State Drive",
    "Graphics Card",
    "RAM Modules",
    "CPU Processor",
    "Motherboard",
    "Power Supply",
    "Cooling Fan",
    "Thermal Paste",
    "Gaming Headset",
    "Smart Watch",
    "Fitness Tracker",
    "Smart Speaker",
    "Security Camera",
    "Video Doorbell",
    "Smart Thermostat",
    "USB Hub",
    "Docking Station",
    "Network Switch",
    "Ethernet Cable",
    "Surge Protector",
    "Battery Pack",
    "Memory Card",
    "Card Reader",
    "Wireless Charger",
    "Streaming Device",
    "Gaming Controller",
    "Capture Card",
    "Drawing Tablet",
    "Portable Projector",
]

STATUSES = ["Ordered", "Confirmed", "Dispatched", "Delivered", "Returned"]

NEW_TENANT_MIN_PRODUCTS = 3
NEW_TENANT_MAX_PRODUCTS = 20
